# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : DefaultColor                │
# └────────────────────────────────────────────┘

$accent  = rgba(1e66f5ee)
$accent2 = rgba(e64553ee)
$border  = rgba(9ca0b0aa)
