# ~/.config/zsh/functions/help.zsh

zsh-help() {
  echo "┌─────────────────────────────────────────────────────────────┐"
  echo "│ 󰊄 Zsh Configuration Help Menu                               │"
  echo "├─────────────────────────────────────────────────────────────┤"
  echo "│ 󰊢 KEYBINDINGS                                              │"
  echo "│   Ctrl+t     - File search & open (fzf)                     │"
  echo "│   Ctrl+f     - Folder search & cd (fzf)                     │"
  echo "│   Ctrl+r     - History search (fzf)                         │"
  echo "│   Ctrl+p     - List installed packages                      │"
  echo "│   Ctrl+y     - Install package (yay)                        │"
  echo "│   Ctrl+v     - Remove package (yay)                         │"
  echo "│   Ctrl+s     - Search package (yay)                         │"
  echo "│   Ctrl+g     - Open SPF file manager                        │"
  echo "│   jk         - Exit insert mode (Vi mode)                   │"
  echo "│                                                             │"
  echo "│ 󰣇 ALIASES                                                   │"
  echo "│   update     - sudo pacman -Syu                             │"
  echo "│   bye        - sudo shutdown -h now                         │"
  echo "│   loop       - sudo reboot                                  │"
  echo "│   n          - nvim                                         │"
  echo "│   hr         - hyprctl reload                               │"
  echo "│   e          - eza --icons                                  │"
  echo "│   el         - eza -lh --icons --git                        │"
  echo "│   ela        - eza -alh --icons --git                       │"
  echo "│   pacupf     - sudo pacman -Syyu                            │"
  echo "│   yupdate    - yay -Syu                                     │"
  echo "│                                                             │"
  echo "│ 󰣇 FUNCTIONS                                                 │"
  echo "│   fastdownload URL    - Download with aria2c                │"
  echo "│   videoconvertmp3     - Convert video to MP3                │"
  echo "│   youtubedownload     - Download from YouTube               │"
  echo "│   battery_status      - Show battery level                  │"
  echo "│                                                             │"
  echo "└─────────────────────────────────────────────────────────────┘"
}
