# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : Campbell                    │
# └────────────────────────────────────────────┘


foreground                      #cccccc
background                      #0c0c0c
selection_background            #ffffff
cursor                          #ffffff
color0                          #0c0c0c
color8                          #767676
color1                          #c50f1f
color9                          #e74856
color2                          #13a10e
color10                         #16c60c
color3                          #f19c00
color11                         #f9f1a5
color4                          #0037da
color12                         #3b78ff
color5                          #881798
color13                         #b4009e
color6                          #3a96dd
color14                         #61d6d6
color7                          #cccccc
color15                         #f2f2f2
active_tab_foreground           #444444
active_tab_background           #ffffff
inactive_tab_foreground         #cccccc
inactive_tab_background         #0a0a0a
