# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : Cobalt2                     │
# └────────────────────────────────────────────┘

foreground                        #FFFFFF
background                        #193549
selection_foreground              #FFFFFF
selection_background              #185294
cursor                            #FFC600
cursor_text_color                 #1C1C1C
url_color                         #00AAFF
active_border_color               #00AAFF
inactive_border_color             #9E9E9E
bell_border_color                 #F2ED7F
active_tab_foreground             #FFC600
inactive_tab_background           #185294
inactive_tab_foreground           #FFFFFF
active_tab_background             #0050A4
tab_bar_background                #193549
mark1_foreground                   #FFC600
mark1_background                   #3AD900
mark2_foreground                   #967EFB
mark2_background                   #00AAFF
mark3_foreground                   #FF628C
mark3_background                   #FF9A00
color0                             #1C1C1C
color8                             #9E9E9E
color1                             #FF0000
color9                             #700009
color2                            #3AD900
color10                           #88FF88
color3                            #FFC600
color11                           #FF9A00
color6                            #80FCFF
color14                           #8fbfdc
color5                            #FF628C
color13                           #EE80E1
color4                            #00AAFF
color12                           #0050A4
color7                            #FFFFFF
color15                           #BCBCBC
