# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       :                             │
# └────────────────────────────────────────────┘
## name: Constant Perceptual Luminosity (dark)

foreground                       #777777
background                       #000000
selection_foreground             #745b00
selection_background             #464646
mark1_foreground                 #000000
mark1_background                 #3123ff
mark2_foreground                 #000000
mark2_background                 #745b00
mark3_foreground                 #000000
mark3_background                 #9b0097
color0                           #000000
color1                           #b10b00
color2                           #007232
color3                           #745b00
color4                           #3123ff
color5                           #9b0097
color6                           #006a78
color7                           #777777
color8                           #464646
color9                           #ff3d2b
color10                           #00ae50
color11                           #b18c00
color12                           #6786ff
color13                           #eb00e4
color14                           #00a3b7
color15                           #ababab

