# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : CoplandOS                   │
# └────────────────────────────────────────────┘


foreground                      #6EBEFF
background                      #001B33
selection_foreground            #000000
selection_background            #6EBEBD
cursor                          #6EBEFF
cursor_text_color               #6EBEFF
color0                          #000000
color8                          #767676
color1                          #cb0102
color9                          #ed3a2c
color2                          #19cb00
color10                         #23fd00
color3                          #f0a300
color11                         #ffbc02
color4                          #605bc6
color12                         #8483f2
color5                          #9c3fa4
color13                         #bb5dc3
color6                          #00d6a6
color14                         #00ffc8
color7                          #dddddd
color15                         #ffffff
