# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Latte                       │
# └────────────────────────────────────────────┘


foreground           #4c4f69
background           #eff1f5
title_fg             #6c6f85
title_bg             #e6e9ef
margin_bg            #e6e9ef
margin_fg            #5c5f77
filler_bg            #e6e9ef
removed_bg           #e6adbc
highlight_removed_bg #e08097
removed_margin_bg    #e397aa
added_bg             #bad8b8
highlight_added_bg   #97c890
added_margin_bg      #e397aa
hunk_margin_bg       #e6e9ef
hunk_bg              #e6e9ef
search_bg            #e8ca9f
search_fg            #4c4f69
select_bg            #a8daf0
select_fg            #4c4f69
