# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Macchiato                   │
# └────────────────────────────────────────────┘


foreground           #cad3f5
background           #24273a
title_fg             #a5adcb
title_bg             #1e2030
margin_bg            #1e2030
margin_fg            #a5adcb
filler_bg            #1e2030
removed_bg           #614455
highlight_removed_bg #895768
removed_margin_bg    #754d5f
added_bg             #4b5d55
highlight_added_bg   #658068
added_margin_bg      #754d5f
hunk_margin_bg       #1e2030
hunk_bg              #1e2030
search_bg            #756c63
search_fg            #cad3f5
select_bg            #455c6d
select_fg            #cad3f5
