# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Mocha                       │
# └────────────────────────────────────────────┘


foreground           #cdd6f4
background           #1e1e2e
title_fg             #a6adc8
title_bg             #181825
margin_bg            #181825
margin_fg            #a6adc8
filler_bg            #181825
removed_bg           #5e3f53
highlight_removed_bg #89556b
removed_margin_bg    #734a5f
added_bg             #475a51
highlight_added_bg   #628168
added_margin_bg      #734a5f
hunk_margin_bg       #181825
hunk_bg              #181825
search_bg            #766c62
search_fg            #cdd6f4
select_bg            #3e5767
select_fg            #cdd6f4
