# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : Adapta Nokto Maia           │
# └────────────────────────────────────────────┘


foreground                        #d8d8d8
background                        #222D31
selection_foreground              #16A085
selection_background              #2B2C2B
url_color                         #0087bd
active_border_color               #00ff00
inactive_border_color             #cccccc
bell_border_color                 #ff5a00
active_tab_foreground             #000
active_tab_background             #eee
inactive_tab_foreground           #444
inactive_tab_background           #999
mark1_background                 #98d3cb
mark2_foreground                 black
mark2_background                 #f2dcd3
mark3_foreground                 black
mark3_background                 #f274bc
color0                           #222D31
color8                           #585858
color1                           #ab4642
color9                           #ab4642
color2                           #7E807E
color10                          #8D8F8D
color3                           #f7ca88
color11                          #f7ca88
color4                           #7cafc2
color12                          #7cafc2
color5                           #ba8baf
color13                          #ba8baf
color6                           #1ABB9B
color14                          #1ABB9B
color7                           #d8d8d8
color15                          #f8f8f8
mark1_foreground black
visual_bell_color               none
tab_bar_background              none
tab_bar_margin_color            none
wayland_titlebar_color          system
macos_titlebar_color            system

