# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : Aquarium Light              │
# └────────────────────────────────────────────┘
## Old BG -> #E6E6F1  #E1E3F2

foreground             #708190
background             #E6E6F1
selection_foreground   #9CA6B9
selection_background   #3D4059
url_color              #7170C2
color0                 #D5D4E0
color8                 #CCCBD9
color1                 #C34864
color9                 #B7435E
color2                 #7D9685
color10                #7E8F80
color3                 #DE956F
color11                #D88B72
color4                 #6A8CBC
color12                #6E7EBF
color5                 #8787BF
color13                #7170C2
color6                 #829FB0
color14                #728A9A
color7                 #313449
color15                #414560
