# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : BlulocoLight                │
# └────────────────────────────────────────────┘


foreground                         #373a41
background                         #f9f9f9
selection_background               #DAF1FF
selection_foreground               #373a41
cursor                             #f32759
cursor_text_color                  #373a41
url_color                          #275FE4
wayland_titlebar_color             #ECECEC
active_tab_foreground              #373a41
active_tab_background              #f9f9f9
inactive_tab_foreground            #929396
inactive_tab_background            #E6E5E5  
tab_bar_background                 #ECECEC
tab_bar_margin_color               none
color0                             #373a41
color8                             #676a77
color1                             #d52753
color9                             #ff6480
color2                             #23974a
color10                            #3cbc66
color3                             #df631c
color11                            #c5a332
color4                             #275fe4
color12                            #0099e1
color5                             #823ff1
color13                            #ce33c0
color6                             #27618d
color14                            #6d93bb
color7                             #babbc2
color15                            #d3d3d3
