# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : BlulocoDark                 │
# └────────────────────────────────────────────┘


foreground                      #b9c0cb
background                      #282c34
selection_foreground            #282c34
selection_background            #b9c0cb
cursor                          #ffcc00
cursor_text_color               #282c34
url_color                       #3375FF
wayland_titlebar_color          #23272F
active_tab_foreground           #b9c0cb 
active_tab_background           #44474D
inactive_tab_foreground         #6B6F79
inactive_tab_background         #1A1F27
tab_bar_background              #23272F
color0                          #41444d
color8                          #8f9aae
color1                          #fc2f52
color9                          #ff6480
color2                          #25a45c
color10                         #3fc56b
color3                          #ff936a
color11                         #f9c859
color4                          #3476ff
color12                         #10b1fe
color5                          #7a82da
color13                         #ff78f8
color6                          #4483aa
color14                         #5fb9bc
color7                          #cdd4e0
color15                         #ffffff
tab_bar_margin_color            none
