# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 15            │
# │ Colors       : Box                         │
# └────────────────────────────────────────────┘



foreground                      #9fef00
background                      #141d2b
selection_foreground            #141d2b
selection_background            #a4b1cd
cursor                          #9fef00
cursor_text_color               #111111
url_color                       #2ee7b6
active_border_color             #00ff00
inactive_border_color           #cccccc
bell_border_color               #ff5a00
active_tab_foreground           #141d2b
active_tab_background           #9fef00
inactive_tab_foreground         #141d2b
inactive_tab_background         #a4b1cd
color0                          #000000
color8                          #767676
color1                          #cc0403
color9                          #f2201f
color2                          #19cb00
color10                         #23fd00
color3                          #cecb00
color11                         #fffd00
color4                          #0d73cc
color12                         #1a8fff
color5                          #cb1ed1
color13                         #fd28ff
color6                          #0dcdcd
color14                         #14ffff
color7                          #dddddd
color15                         #ffffff

tab_bar_background              none
tab_bar_margin_color            none
visual_bell_color               none
wayland_titlebar_color          system
