# ┌────────────────────────────────────────────┐
# │        Kitty Terminal Configuration        │
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# └────────────────────────────────────────────┘


#  ┌────────────────────────────────────────────┐
#  │      Kitty Terminal Themes Switch link     │
#  └────────────────────────────────────────────┘
include current-theme.conf



font_family JetBrainMono #FantasqueSansM Nerd Font Mono Bold
font_size 12.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.9
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1
mouse_hide_wait 3.0
cursor_shape block
cursor_stop_blinking_after 15.0


# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1
scrollbar_hitbox_expansion 0.25


enable_audio_bell no
window_padding_width 4

allow_remote_control yes

# background_image ~/.config/bubuicon/butilove.png
# background_image_layout centered
# background_image_linear yes
# background_tint 0.86

# Layout setting
enabled_layouts splits,stack


# ============================================
# Window Management
# ============================================

# Split Windows
map ctrl+alt+enter launch --location=vsplit
map ctrl+alt+shift+enter launch --location=hsplit

# Window Navigation
map alt+l neighboring_window left
map alt+h neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Window Close
map ctrl+q close_window
map ctrl+shift+w no_op
map ctrl+d no_op


# Window Layout
map ctrl+shift+r load_config_file
map ctrl+alt+r next_layout
map ctrl+alt+shift+r previous_layout
# ============================================
# Tab Management
# ============================================

# Tab Navigation
map alt+t new_tab
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab
map alt+w close_tab

# Tab Movement
map ctrl+shift+alt+l move_tab_forward
map ctrl+shift+alt+h move_tab_backward

# ============================================
# Misc
# ============================================

# Close Kitty entirely
map ctrl+shift+q quit

# Reload config
map ctrl+shift+r load_config_file

# Copy/Paste (optional)
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
